# Generated by Django 3.1.4 on 2021-08-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20210830_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='time',
            field=models.DecimalField(decimal_places=6, default=123458, max_digits=15),
            preserve_default=False,
        ),
    ]
