# Generated by Django 3.1.4 on 2021-08-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_service_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('time', models.DecimalField(decimal_places=3, max_digits=30)),
            ],
            options={
                'verbose_name': 'SetService',
                'verbose_name_plural': 'Set Services',
                'ordering': ('-id',),
            },
        ),
    ]
